---
script: "bundle exec rubytest -Itest -Ilib test/test*"
bundler_args: --without compiled
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
notifications:
  recipients:
    - transfire@gmail.com
matrix:
  allow_failures:
    - rvm: jruby-19mode


